version: '3.5'
services:
  apione: 
    build: ./rinhadelangs
    hostname: apione
    image: apione:latest
    container_name: apione
    depends_on:
      - db
    environment:
      PORT: "8081"
    expose:
      - "8081"
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1GB'
    network_mode: "host"

  apitwo: 
    build: ./rinhadelangs
    hostname: apitwo
    image: apitwo:latest
    container_name: apitwo
    depends_on:
      - db
    environment:
      PORT: "8082"
    expose:
      - "8082"
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1GB'
    network_mode: "host"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apione
      - apitwo
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.3GB'
    network_mode: "host"

  db: # Banco de dados
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinhadb
    hostname: postgres
    command: postgres -c 'max_connections=450'
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.7GB'
